services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run test:watch
